# ----- Datasource settings -----
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345
    url: jdbc:postgresql://localhost:5432/bookstore
    username: root
  # ----- Jpa and Hibernate settings -----
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  # ----- Liquibase (DB Migration Tool) settings -----
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: false